### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [James-Coulson/CITS3002-Project-Final#1]
Hey James-Coulson!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by James-Coulson** [comment]
Please refer to the University of Western Australia's [academic assessment policy](https://www.uwa.edu.au/policy/-/media/Project/UWA/UWA/Policy-Library/Policy/Teaching-and-Research-Training/Learning-and-Teaching/Assessment/Assessment-Policy.doc), section 5.10, specifically part 1;

(1) Students hold the intellectual property inherent in all work produced for assessments.

Under the university's own policy, it is not up to the university to dictate what a student does with the answers to an assessment, including publishing them openly on GitHub.

Because of this I will be closing this issue.
